name: flutter_netflix_clone
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  carousel_slider: ^4.2.1
  collection: ^1.17.2
  url_launcher: ^6.1.14
  firebase_core: ^2.19.0
  cloud_firestore: ^4.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  freezed: ^2.4.5
  json_serializable: ^6.7.1





flutter:




  uses-material-design: true
  assets:
    - assets/
    - assets/poster/
































