///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class Assets {
  Assets._();

  static const String assetsEogflixLogo = 'assets/eogflix_logo.png';
  static const String posterTestMovie1 = 'assets/poster/test_movie_1.png';
}
